version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  groups: 
    xunit:
        patterns:
          - "xunit"
          - "xunit.runner.visualstudio"
    nuget:
        patterns:
          - "NuGet.Packaging.Core"
          - "NuGet.Protocol"
  open-pull-requests-limit: 25
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
