<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="current">

    <Import Project="..\Snap\Snap.Deps.targets" />
    <Import Project="Snap.Installer.Deps.targets" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Snap.Installer</RootNamespace>
        <AssemblyName>Snap.Installer</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <!-- /p:PublishTrimmed=true -->
    <!-- https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md#available-feature-switches -->
    <PropertyGroup Condition="$(OsPlatform) == 'Windows'">
        <!-- Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com -->
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0' And '$(AvaloniaBuildTasksLocation)' == ''">
        <AvaloniaBuildTasksLocation>$(NuGetPackageRoot)avalonia\$(AvaloniaVersion)\build\Avalonia.Build.Tasks.dll</AvaloniaBuildTasksLocation>
        <UsingAvaloniaNet10Workaround>true</UsingAvaloniaNet10Workaround>
    </PropertyGroup>

    <Target Name="DetectAvaloniaOfficialSupport" BeforeTargets="CoreCompile" Condition="'$(UsingAvaloniaNet10Workaround)' != 'true'">
        <Error Text="🎉 Avalonia now officially supports .NET 10.0! Please remove the workaround in Snap.Installer.csproj and use official support." />
    </Target>

    <ItemGroup>
        <EmbeddedResource Include="Assets\**\*" />
        <EmbeddedResource Remove="Assets\AssetsTypeRoot.cs" />
        <EmbeddedResource Include="../Snap.CoreRun/src/resources/CoreRun.ico" Link="Assets\snap.ico" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
        </Compile>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Snap\Snap.csproj" />
    </ItemGroup>

</Project>
